Taller/Taller1/Models/ErrorViewModel.cs
namespace Taller1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Taller/Taller1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Taller1.Models;

namespace Taller1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Taller/Taller1/Controllers/LaboratorioController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace Taller1.Controllers
{
    public class LaboratorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<LaboratorioCLS> filtrarLaboratorio(LaboratorioCLS objLaboratorio)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.FiltrarLaboratorios(objLaboratorio.nombre, objLaboratorio.direccion, objLaboratorio.personaContacto);
        }

        public LaboratorioCLS recuperarLaboratorio(int id)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.recuperarLaboratorios(id);
        }

        public int guardarLaboratorio(LaboratorioCLS objLaboratorio)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.GuardarLaboratorios(objLaboratorio);
        }

        public int eliminarLaboratorio(int id)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.eliminarLaboratorios(id);
        }
    }
}

Taller/Taller1/Controllers/MedicamentoController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace Taller1.Controllers
{
    public class MedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<MedicamentoCLS> filtrarMedicamento(MedicamentoCLS medicamentoCLS)
        {
            MedicamentoDAL obj = new MedicamentoDAL();
            return obj.FiltrarMedicamento(medicamentoCLS);
        }

        public MedicamentoCLS recuperarMedicamento(int id)
        {
            MedicamentoDAL obj = new MedicamentoDAL();
            return obj.recuperarMedicamento(id);
        }

        public int guardarMedicamento(MedicamentoCLS medicamentoCLS)
        {
            MedicamentoDAL obj = new MedicamentoDAL();
            return obj.guardarMedicamento(medicamentoCLS);
        }

        public int eliminarMedicamento(int id)
        {
            MedicamentoDAL obj = new MedicamentoDAL();
            return obj.eliminarMedicamento(id);
        }

    }
}

Taller/Taller1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}




<h1>Tipo Medicamento</h1>

<div class="modal fade" id="operacionesModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Formulario de Laboratorio</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="frmOperaciones">
                    <div class="mb-3">
                        <label for="idTipoMedicamento" class="form-label">ID Laboratorio</label>
                        <input type="text" class="form-control" name="idTipoMedicamento" id="frmOperaciones" value="0" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="descripcion" class="form-label">Dirección</label>
                        <input type="text" class="form-control" name="descripcion" id="frmOperaciones" value=" ">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="guardarTipoMedicamento()" data-bs-dismiss="modal" class="btn btn-success">Enviar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            </div>
        </div>
    </div>
</div>


<fieldset class="p-4 border rounded-3">
    <legend class="fs-5 fw-bold">Filtrar</legend>
    <form id="frmFiltrar">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="txtNombre" id="frmOperaciones" value=" ">
        </div>
    </form>
    <button type="button" onclick="filtrarTipoMedicamento()" class="btn btn-success">Enviar</button>
    <button type="button" onclick="limpiarTipoMedicamento()" class="btn btn-secondary">Salir</button>
</fieldset>

<div id="divTable">

</div>

<script src="~/js/tipoMedicamento.js"></script>
<script src="~/js/queries.js"></script>

Taller/Taller1/Views/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Taller/Taller1/Views/Laboratorio/Index.cshtml
@{
    ViewData["Title"] = "Laboratorios";
}

<h1>Laboratorios</h1>

<div class="modal fade" id="operacionesModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Formulario de Laboratorio</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="frmOperaciones">
                    <div class="mb-3">
                        <label for="idLaboratorio" class="form-label">ID Laboratorio</label>
                        <input type="text" class="form-control" name="idLaboratorio" id="frmOperaciones" value="0" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="direccion" class="form-label">Dirección</label>
                        <input type="text" class="form-control" name="direccion" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="personaContacto" class="form-label">Persona de Contacto</label>
                        <input type="text" class="form-control" name="personaContacto" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="numeroContacto" class="form-label">Número de Contacto</label>
                        <input type="tel" class="form-control" name="numeroContacto" id="frmOperaciones" value=" ">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="guardarLaboratorio()" data-bs-dismiss="modal" class="btn btn-success">Enviar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            </div>
        </div>
    </div>
</div>

<fieldset class="p-4 border rounded-3">
    <legend class="fs-5 fw-bold">Buscar</legend>
    <form id="frmFiltrar">
        <div class="mb-3">
            <label for="idLaboratorio" class="form-label">ID Laboratorio</label>
            <input type="text" class="form-control" name="idLaboratorio" id="frmOperaciones" value="0" readonly>
        </div>
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="frmOperaciones" value="">
        </div>
        <div class="mb-3">
            <label for="direccion" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="direccion" id="frmOperaciones" value="">
        </div>
        <div class="mb-3">
            <label for="personaContacto" class="form-label">Persona de Contacto</label>
            <input type="text" class="form-control" name="personaContacto" id="frmOperaciones" value="">
        </div>
        <div class="mb-3">
            <label for="numeroContacto" class="form-label">Número de Contacto</label>
            <input type="tel" class="form-control" name="numeroContacto" id="frmOperaciones" value="">
        </div>
    </form>
    <button type="button" onclick="filtrarLaboratorio()" class="btn btn-success">Filtrar</button>
    <button type="button" onclick="limpiarLaboratorio()" class="btn btn-secondary">Salir</button>
</fieldset>


<div id="divTable">
</div>

<script src="~/js/laboratorio.js"></script>
<script src="~/js/queries.js"></script>

Taller/Taller1/Views/Medicamento/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Medicamento</h1>




<div class="modal fade" id="operacionesModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Formulario de Laboratorio</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="frmOperaciones">
                    <div class="mb-3">
                        <label for="idMedicamento" class="form-label">ID Medicamento</label>
                        <input type="text" class="form-control" name="idMedicamento" id="frmOperaciones" value="0" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="codigo" class="form-label">Codigo</label>
                        <input type="text" class="form-control" name="codigo" id="frmOperaciones" value="">
                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="idLab" class="form-label">Id Lab</label>
                        <input type="text" class="form-control" name="idLab" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="idTipoMed" class="form-label">id Tipo med</label>
                        <input type="text" class="form-control" name="idTipoMed" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="uso" class="form-label">Uso</label>
                        <input type="tel" class="form-control" name="uso" id="frmOperaciones" value=" ">
                    </div><div class="mb-3">
                        <label for="contenido" class="form-label">contenido</label>
                        <input type="tel" class="form-control" name="contenido" id="frmOperaciones" value=" ">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="guardarMedicamento()" data-bs-dismiss="modal" class="btn btn-success">Enviar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            </div>
        </div>
    </div>
</div>

<fieldset class="p-4 border rounded-3">
    <legend class="fs-5 fw-bold">Filtrar</legend>
    <form id="frmFiltrar">
        <div class="mb-3">
            <label for="idMedicamento" class="form-label">ID Medicamento</label>
            <input type="text" class="form-control" name="idMedicamento" id="frmOperaciones" value="">
        </div>
        <div class="mb-3">
            <label for="codigo" class="form-label">Codigo</label>
            <input type="text" class="form-control" name="codigo" id="frmOperaciones" value="">
        </div>
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="frmOperaciones" value=" ">
        </div>
        <div class="mb-3">
            <label for="idLab" class="form-label">Id Lab</label>
            <input type="text" class="form-control" name="idLab" id="frmOperaciones" value=" ">
        </div>
        <div class="mb-3">
            <label for="idTipoMed" class="form-label">id Tipo med</label>
            <input type="text" class="form-control" name="idTipoMed" id="frmOperaciones" value=" ">
        </div>
        <div class="mb-3">
            <label for="uso" class="form-label">Uso</label>
            <input type="tel" class="form-control" name="uso" id="frmOperaciones" value=" ">
        </div><div class="mb-3">
            <label for="contenido" class="form-label">contenido</label>
            <input type="tel" class="form-control" name="contenido" id="frmOperaciones" value=" ">
        </div>
    </form>
    <button type="button" onclick="filtrarMedicamento()" class="btn btn-success">Enviar</button>
    <button type="button" onclick="limpiarMedicamento()" class="btn btn-secondary">Salir</button>
</fieldset>

<div id="divTable">

</div>

<script src="~/js/medicamento.js"></script>
<script src="~/js/queries.js"></script>

Taller/Taller1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taller1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Taller1.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>

</head>
<body>
    <!-- Navbar superior -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Taller1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Sidebar (Panel lateral) -->
    <div class="sidebar">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-home me-2"></i> Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="SinMenu">
                    <i class="fas fa-list me-2"></i> SinMenu
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="Index">
                    <i class="fas fa-store me-2"></i> Sucursal
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorio" asp-action="Index">
                    <i class="fas fa-flask me-2"></i> Laboratorio
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Medicamento" asp-action="Index">
                    <i class="fas fa-pills me-2"></i> Medicamento
                </a>
            </li>
        </ul>
    </div>

    <!-- Contenido principal -->
    <div class="content">
        <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Taller1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Taller/Taller1/Views/Sucursal/Index.cshtml
@{
    ViewData["Title"] = "Sucursales";
}


<h1>Sucursales</h1>

<div class="modal fade" id="operacionesModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Formulario de Laboratorio</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="frmOperaciones">
                    <div class="mb-3">
                        <label for="idSucursal" class="form-label">ID Laboratorio</label>
                        <input type="text" class="form-control" name="idSucursal" id="frmOperaciones" value="0" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" id="frmOperaciones" value=" ">
                    </div>
                    <div class="mb-3">
                        <label for="direccion" class="form-label">Dirección</label>
                        <input type="text" class="form-control" name="direccion" id="frmOperaciones" value=" ">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="guardarSucursal()" data-bs-dismiss="modal" class="btn btn-success">Enviar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            </div>
        </div>
    </div>
</div>

<fieldset>
	<legend>Filtrar</legend>
	<form id="frmFiltrar">
		<div class="mb-3">
			<label for="idSucursal" class="form-label">ID Sucursal</label>
			<input type="text" class="form-control" name="idSucursal" id="frmOperaciones" value="0" readonly>
		</div>
		<div class="mb-3">
			<label for="nombre" class="form-label">Nombre</label>
			<input type="text" class="form-control" name="nombre" id="frmOperaciones" value="">
		</div>
		<div class="mb-3">
			<label for="direccion" class="form-label">Dirección</label>
			<input type="text" class="form-control" name="direccion" id="frmOperaciones" value="">
		</div>
	</form>
	<button type="button" onclick="filtrarSucursal()" class="btn btn-success">Filtrar</button>
	<button type="button" onclick="limpiarSucursal()" class="btn btn-secondary">Salir</button>
</fieldset>


<br />

<div id="divTable">
</div>



<script src="~/js/queries.js"></script>
<script src="~/js/Sucursales.js"></script>

Taller/Taller1/Views/TipoMedicamento/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Taller/Taller1/Views/TipoMedicamento/inicio.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}